
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { toast } from "sonner";

const SUPABASE_URL = "https://fyyvrhyfgnbnhmjmjful.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5eXZyaHlmZ25ibmhtam1qZnVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1MTYwMDAsImV4cCI6MjA1NzA5MjAwMH0.uJJu8uKKoh3bwN2xQLpNeQZN-aWU2mcMjHsmHrI3EFI";

// Create client with additional options for better error handling
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
    },
    global: {
      headers: {
        'Content-Type': 'application/json',
      },
      fetch: (...args) => {
        console.log("Supabase fetch request:", args[0]);
        return fetch(...args);
      },
    },
  }
);

// Add a helper function to check connection status
export const checkSupabaseConnection = async () => {
  try {
    const { data, error } = await supabase.from('clients').select('count');
    if (error) {
      console.error("Supabase connection test failed:", error);
      toast.error("Verbindung zur Datenbank fehlgeschlagen");
      return false;
    }
    console.log("Supabase connection test successful");
    return true;
  } catch (err) {
    console.error("Supabase connection test error:", err);
    toast.error("Verbindung zur Datenbank fehlgeschlagen");
    return false;
  }
};

// Log auth state changes
supabase.auth.onAuthStateChange((event, session) => {
  console.log("Auth state changed:", event, session ? "User logged in" : "No user");
});
