
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fyyvrhyfgnbnhmjmjful.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5eXZyaHlmZ25ibmhtam1qZnVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1MTYwMDAsImV4cCI6MjA1NzA5MjAwMH0.uJJu8uKKoh3bwN2xQLpNeQZN-aWU2mcMjHsmHrI3EFI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

console.log("Supabase Client initialisiert mit URL:", SUPABASE_URL);

// Create client with additional options for better error handling
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
    },
    global: {
      fetch: (url, options) => {
        console.log("Supabase fetch request:", url);
        return fetch(url, options);
      },
    },
  }
);

// Add a helper function to check connection status
export const checkSupabaseConnection = async () => {
  try {
    const { error } = await supabase.from('clients').select('count');
    if (error) {
      console.error("Supabase connection test failed:", error);
      return false;
    }
    console.log("Supabase connection test successful");
    return true;
  } catch (err) {
    console.error("Supabase connection test error:", err);
    return false;
  }
};
